const ERROR_CODES = Object.freeze({
  SUCCESS: 0,
  PARAM_ERROR: 40001,
  UNAUTHORIZED: 40003,
  BOOKING_VERIFY_FAILED: 40004,
  FORBIDDEN: 40301,
  NOT_FOUND: 40401,
  STOCK_INSUFFICIENT: 40901,
  ORDER_STATUS_CONFLICT: 40902,
  TOO_MANY_REQUESTS: 42901,
  INTERNAL_ERROR: 50001,
  PAYMENT_SERVICE_ERROR: 50002
})

const ERROR_MESSAGES = Object.freeze({
  [ERROR_CODES.SUCCESS]: "ok",
  [ERROR_CODES.PARAM_ERROR]: "参数错误",
  [ERROR_CODES.UNAUTHORIZED]: "未登录或登录态失效",
  [ERROR_CODES.BOOKING_VERIFY_FAILED]: "预订校验失败",
  [ERROR_CODES.FORBIDDEN]: "无权限访问",
  [ERROR_CODES.NOT_FOUND]: "数据不存在",
  [ERROR_CODES.STOCK_INSUFFICIENT]: "库存不足",
  [ERROR_CODES.ORDER_STATUS_CONFLICT]: "订单状态冲突",
  [ERROR_CODES.TOO_MANY_REQUESTS]: "请求过于频繁",
  [ERROR_CODES.INTERNAL_ERROR]: "服务器内部错误",
  [ERROR_CODES.PAYMENT_SERVICE_ERROR]: "支付服务异常"
})

function resolveErrorMessage(code) {
  return ERROR_MESSAGES[code] || ERROR_MESSAGES[ERROR_CODES.INTERNAL_ERROR]
}

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES,
  resolveErrorMessage
}
